### PR TITLE
"Release 0.4.0"

### PR DESCRIPTION
**Pull request by pwilczynskiclearcode**
Anything preventing us from releasing new version?

### CODE REVIEW

**Comment by fizyk** [comment]
I'd like to get at least #40 done for 0.4 documentation would be nice, although not required.

**Comment by pwilczynskiclearcode** [comment]
Sure, your call.

**Comment by fizyk** [comment]
How will you include tags in Pull Request?

**Comment by pwilczynskiclearcode** [comment]
You can create tag

**Pull request closed without merging**
