### PR TITLE
Changing build matrix into manual steps - finally running tests on osx

### PR DESCRIPTION
**Pull request by fizyk**

### CODE REVIEW

**Comment by fizyk** [comment]
finally got the tests on osx running. 

We'll be able to start working on failures, but from what I can tell it's more the  underlying commands difference that we use.

**Comment by tomislater** [comment]
Hmm, but it will work only with python 3.5 on OSX, right?

**Comment by fizyk** [comment]
yeah,

the python implementation shouldn't be actually that different between versions and platforms, so I figured at least one run on osx would be good enough to cover differences on osx itself.

**Comment by tomislater** [comment]
kk :+1:

**Pull request merged**
