### PR TITLE
112 bugfix: Handle IOErrors from psutil

### PR DESCRIPTION
**Pull request by pwilczynskiclearcode**

### CODE REVIEW

**Comment by pwilczynskiclearcode** [comment]
@mmaslowskicc please, review

**Comment by mmaslowskicc** [comment]
Ok, while I don't know when this exception could occur.

**Comment by pwilczynskiclearcode** [comment]
@mmaslowskicc #114 I'm not sure too. Either current user has no access to given process `environ` or the process was killed since '/proc/28368/environ' existence check.

**Comment by mmaslowskicc** [comment]
Ok, so either the process was killed (and doesn't need to be killed by us) or we can't kill it (not having the permission).

**Pull request merged**
